// ข้อมูลสินค้าทั้งหมด - แก้ไขที่นี่จุดเดียวแล้วมีผลทุกหน้า
export const productsData = {
  1: {
    name: "Luxury Leaderboard",
    price: 300,
    tags: ["BP"],
    category: "แอดออน",
    author: "BarryAroy",
    images: [
      "/images/luxury-leaderboard-cover.png",
      "/images/luxury-leaderboard1.png",
      "/images/luxury-leaderboard2.png",
      "/images/luxury-leaderboard3.png",
      "/images/luxury-leaderboard4.png",
      "/images/luxury-leaderboard5.png",
      "/images/luxury-leaderboard6.png",
    ],
    description: "อักษรลอยและกระดานผู้นำสุดเฟี้ยวไม่เหมือนที่ไหน ระบบที่จะทำให้เซิร์ฟเวอร์ของคุณดูโปรและน่าประทับใจมากขึ้น",
    features: [
      "ป้องกัน kill @e",
      "ไม่ใช้ Resourcepack",
      "ป้องกัน Player Offline ในกระดานผู้นำ",
      "อักษรลอยสวยงามและปรับแต่งได้",
      "กระดานผู้นำแบบเรียลไทม์",
    ],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  2: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["Map"],
    category: "แมพ",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  3: {
    name: "Savage Impaler",
    price: 150,
    tags: ["RP"],
    category: "รีซอสแพ็ค",
    author: "BarryAroy",
    images: [
      "/images/savage-impaler-cover.png",
      "/images/savage-impaler1.png",
      "/images/savage-impaler2.png",
      "/images/savage-impaler3.png",
      "/images/savage-impaler4.png",
      "/images/savage-impaler5.png",
    ],
    description: "รีซอสมองทะลุอัพเกรดที่มาพร้อมกับการเจาะระบบห้ามใช้รีซอสแพ็คนอกในกรณีที่บางแมพ หรือบางเซิฟเวอร์ห้ามใช้รีซอสแพ็คนอก",
    features: ["ทะลุการป้องกันห้ามใช้รีซอสแพ็คนอกแมพ", "มองเห็น entity ทะลุกำแพงได้ทุกรูปแบบ"],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  4: {
    name: "Player Honor",
    price: 300,
    tags: ["BP"],
    category: "แอดออน",
    author: "BarryAroy",
    images: [
      "/images/player-honor-cover.png",
      "/images/player-honor1.png",
      "/images/player-honor2.png",
      "/images/player-honor3.png",
      "/images/player-honor4.png",
      "/images/player-honor5.png",
    ],
    description: "แก้ไขชื่อผู้เล่นและยศได้อย่างอิสระ และมีระบบแบนคำหยาบคายต่างๆในแชท",
    features: ["แก้ไขชื่อผู้เล่นได้อิสระ", "แก้ไขยศของผู้เล่นได้อิสระ", "แบนคำหยาบคายในการพิมพ์แชท", "การแสดงผลแชทที่ดีขึ้นเพื่อพิมพ์ข้อความ"],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  5: {
    name: "Frenzied Crafting",
    price: 300,
    tags: ["BP"],
    category: "แอดออน",
    author: "BarryAroy",
    images: [
      "/images/frenzied-crafting-cover.png",
      "/images/frenzied-crafting1.png",
      "/images/frenzied-crafting2.png",
      "/images/frenzied-crafting3.png",
      "/images/frenzied-crafting4.png",
      "/images/frenzied-crafting5.png",
    ],
    description: "กำหนดเปอร์เซ็นต์คราฟไอเท็มสำเร็จ และกำหนดจำนวนไอเท็มในการใช้คราฟได้หลายชิ้นถึงหลักร้อยขึ้นก็ยังได้",
    features: [
      "กำหนดบล็อคโต๊ะคราฟได้",
      "กำหนดเปอร์เซ็นต์ที่จะคราฟไอเท็มสำเร็จได้",
      "กำหนดจำนวนไอเท็มคราฟได้",
      "ทำให้ชีวิตนักฟาร์มในโลกของคุณยากรันทดขึ้น",
    ],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  6: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["RP"],
    category: "รีซอสแพ็ค",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  7: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["Map"],
    category: "แมพ",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  8: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["CMD"],
    category: "คอมมานด์",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  9: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["CMD"],
    category: "คอมมานด์",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  10: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["CMD"],
    category: "คอมมานด์",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  11: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["APP"],
    category: "แอพเสริม",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  12: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["APP"],
    category: "แอพเสริม",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  13: {
    name: "ยังไม่มีสินค้า",
    price: 999,
    tags: ["APP"],
    category: "แอพเสริม",
    author: "BarryAroy",
    images: ["/images/nothing_404.png", "/images/nothing_404.png", "/images/nothing_404.png"],
    description: "...",
    features: ["..."],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  14: {
    name: "Gacha Plus",
    price: 250,
    tags: ["BP"],
    category: "แอดออน",
    author: "BarryAroy",
    images: [
      "/images/gacha-plus-cover.png",
      "/images/gacha-plus-promo.png",
      "/images/gacha-plus1.png",
      "/images/gacha-plus2.png",
      "/images/gacha-plus3.png",
      "/images/gacha-plus4.png",
      "/images/gacha-plus5.png",
      "/images/gacha-plus6.png",
    ],
    description: "ระบบสุ่มกาชาและเรตการสุ่มสุดเฟี้ยว พร้อมไอเท็มการันตีการสุ่ม",
    features: ["กำหนดเรตการสุ่มอย่างเฟี้ยว", "ดูเรตการสุ่มไอเท็มแต่ละหมวดได้", "สุ่มกาชาได้ตามเรตโดยไม่บัคค่า % แน่นอน"],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  15: {
    name: "รับทำเว็บไซต์",
    price: 350,
    tags: ["WEB"],
    category: "เว็บไซต์",
    author: "BarryAroy",
    images: [
      "/images/website-cover.png",
      "/images/website-new1.png",
      "/images/website-new2.png",
      "/images/website-new3.png",
      "/images/website-new4.png",
      "/images/website-new5.png",
      "/images/website-new6.png",
      "/images/website-new7.png",
      "/images/website-new8.png",
      "/images/website-new9.png",
    ],
    description: "รับทำเว็บไซต์รูปแบบต่างๆตามที่บรีฟงาน และตกลงกันไว้",
    features: [
      "โดเมนฟรีถาวร",
      "เชื่อมหน้าเว็บอื่นๆได้",
      "มีฐานข้อมูลให้ใช้ฟรีถาวร",
      "กำหนดหลายๆอย่างอิสระ",
      "หน้าต่างรองรับทุกแพลตฟอร์ม",
      "กำหนดชื่อในโดเมนได้อิสระ 50 ชื่อ",
      "ใช้งานสะดวกและเร็วแรง ออกแบบมาดี",
      "ติดตั้งเป็นแอพได้ในหลายๆแพลตฟอร์ม",
      "สามารถทำหน้าเว็บที่เข้าได้เฉพาะแอดมิน",
    ],
    compatibility: "ทุกแพลตฟอร์ม",
  },
  16: {
    name: "ระบบรีวิวให้ดาว",
    price: 450,
    tags: ["WEB"],
    category: "เว็บไซต์",
    author: "BarryAroy",
    images: [
      "/images/review-system-cover.png",
      "/images/review-system-new1.png",
      "/images/review-system-new2.png",
      "/images/review-system-new3.png",
      "/images/review-system-new4.png",
    ],
    description: "รับทำเว็บไซต์รูปแบบต่างๆตามที่บรีฟงาน และตกลงกันไว้",
    features: [
      "มีฐานข้อมูลให้จัดการและดูแล",
      "ป้องกันคนนอกคอมเมนท์เล่นได้",
      "มีหน้าสำหรับแอดมินให้จัดการสิ่งต่างๆ",
      "นำไปเชื่อม หรือ แสดงในหน้าเว็บอื่นๆได้",
      "แสดงจำนวนผู้รีวิวทั้งหมดและสรุปให้ละเอียด",
      "ดึงข้อมูลผู้คอมเม้นท์จากไอดีผู้ใช้ Discord ปลอดภัย",
    ],
    compatibility: "ทุกแพลตฟอร์ม",
  },
  17: {
    name: "Female Core",
    price: 200,
    tags: ["BP & RP"],
    category: "แอดออน",
    author: "BarryAroy & Thaideity",
    images: ["/images/female-core-cover.png", "/images/female-core-promo.png", "https://youtu.be/PE3XG_Uvss0"],
    description: "สกินผู้เล่นมีหน้าอกทรงค่อนข้างกลม พร้อมอนิเมชั่นหน้าอกเด้งอย่างลื่นไหล",
    features: [
      "เป็นชุดเกราะสวมใส่ท่อนไหนก็ได้เช่น หัว ตัว ขา เท้า",
      "ไม่ใช้ player.json ในรีซอสแพ็ค",
      "รองรับอนิเมชั่นอื่นๆเช่น Actions & Stuff",
      "รองรับสกินผู้เล่นปกติทั่วไป",
      "รองรับสกินคมชัด",
      "หน้าอกไม่เหลี่ยม",
      "หน้าอกเด้งดึ๋งๆใช้เพื่อข่มขวัญคนอื่นได้",
      "ทำเป็นสกินชุดเกราะในตัวเกมได้",
    ],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  18: {
    name: "ThaiTech Ring",
    price: 69,
    tags: ["BP & RP"],
    category: "แอดออน",
    author: "BarryAroy",
    images: [
      "/images/thaitech-ring-cover.png",
      "/images/thaitech-ring1.png",
      "/images/thaitech-ring2.png",
      "/images/thaitech-ring3.png",
      "/images/thaitech-ring4.png",
      "/images/thaitech-ring5.png",
      "https://youtu.be/sHYUvObW3gU?si=SD8ZvvXH9WctXv0O",
    ],
    description: "วงแหวนลายไทยเรืองแสงส่องสว่างแดงฉาน ว่ากันว่าวงแหวนนี้ไม่ชอบให้ผู้สวมใส่นอนลาบลง",
    features: [
      "เป็นชุดเกราะสวมใส่ท่อนไหนก็ได้เช่น หัว ตัว ขา เท้า",
      "ไม่ใช้ player.json ในรีซอสแพ็ค",
      "รองรับอนิเมชั่นอื่นๆเช่น Actions & Stuff",
      "เรืองแสงในที่มืด",
      "เปลี่ยนรูปวงแหวนได้หากลูกค้ามีมาให้",
      "ทำเป็นสกินชุดเกราะในตัวเกมได้",
    ],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  19: {
    name: "BitCommands",
    price: 100,
    tags: ["BP"],
    category: "แอดออน",
    author: "BarryAroy",
    images: [
      "/images/bitcommands-cover.png",
      "/images/bitcommands1.png",
      "/images/bitcommands2.png",
      "/images/bitcommands3.png",
      "/images/bitcommands4.png",
      "/images/bitcommands5.png",
    ],
    description: "เพิ่มคอมมานใหม่อย่างอิสระลงในโลกของท่าน เพื่อความสะดวกต่อการใช้งานต่างๆ",
    features: [
      "กำหนดได้หลายคอมมาน",
      "กำหนดได้ว่าแต่ละคอมมานใครใช้ได้บ้าง",
      "มีข้อความที่กำหนดแสดงเมื่อเข้าออกโลกใหม่",
      "ใช้งานง่ายๆเช่น /hub หรือ /mb:hub",
    ],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  20: {
    name: "MineBit Display",
    price: 300,
    tags: ["BP"],
    category: "แอดออน",
    author: "BarryAroy",
    images: [
      "/images/minebit-display-cover.png",
      "/images/minebit-display1.png",
      "/images/minebit-display2.png",
      "https://youtu.be/iMyc6eLl-04?si=81k1Ax1iTG9M3wnD",
    ],
    description: "ไม่ต้องมีรีซอสแพ็คก็สามารถแสดงจำนวนดาเมจที่ทำได้และอื่นๆมากมาย",
    features: [
      "ไม่ใช้รีซอสแพ็คใดๆ",
      "แสดงดาเมจที่ทำได้ (จำนวนเท่าที่เกมทำได้ 2.1 พันล้าน)",
      "แสดงจำนวนเลือดที่ผื้นฟูได้ (จำนวนเท่าที่เกมทำได้ 2.1 พันล้าน)",
      "แสดงเลือด และ ชื่อบนหัว",
      "แบนคำหยาบในแชทเกม",
      "ยศบนหัว และ ในแชทเกม",
    ],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  21: {
    name: "Ponytail Hairstyle",
    price: 75,
    tags: ["BP & RP"],
    category: "แอดออน",
    author: "BarryAroy & Thaideity",
    images: [
      "/images/ponytail-cover.png",
      "/images/ponytail1.png",
      "/images/ponytail2.png",
      "/images/ponytail3.png",
      "/images/ponytail4.png",
      "https://youtu.be/8r7KW4dY53M",
    ],
    description: "ผมหางม้าปลิวไสวยื่นออกมา ให้ออร่าจับดุจองค์ราชินีจันทร์เพ็ญ",
    features: [
      "ออร่าจับดุจองค์ราชินี",
      "มีอนิเมชั่นเมื่อเคลื่อนไหวตัวละคร",
      "กำหนดตำแหน่งผมได้",
      "กำหนดอนิเมชั่นได้",
      "เมื่อก้มหรือเงยหน้าผมไม่บัคสิงเข้าตัว",
    ],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
  22: {
    name: "Great Amulets",
    price: 100,
    tags: ["BP & RP"],
    category: "แอดออน",
    author: "BarryAroy",
    images: [
      "/images/great-amulets-cover.png",
      "/images/great-amulets1.png",
      "/images/great-amulets2.png",
      "/images/great-amulets3.png",
      "https://www.youtube.com/watch?v=YCGUw6LiZmE",
    ],
    description: "สวมใส่ไอเท็มในช่องเครื่องรางได้ โดยช่องเครื่องรางแยกจากช่องเก็บของในตัว",
    features: ["สวมใส่ไอเท็มในช่องเครื่องรางได้", "รับความสามารถต่างๆของไอเท็มสวมใส่", "ช่องเครื่องรางแยกจากช่องเก็บของในตัว"],
    compatibility: "Minecraft Bedrock 1.21.9x+",
  },
}

// ข้อมูลหมวดหมู่
export const categoriesData = {
  addons: {
    name: "แอดออน",
    description: "เพิ่มฟีเจอร์ใหม่และความสามารถพิเศษให้กับเกม Minecraft",
    availableTags: ["BP", "BP & RP"],
    productIds: [22, 21, 20, 19, 18, 17, 14, 5, 4, 1],
  },
  "resource-packs": {
    name: "รีซอสแพ็ค",
    description: "เปลี่ยนการแสดงผลภาพ",
    availableTags: ["RP"],
    productIds: [3],
  },
  maps: {
    name: "แมพ",
    description: "โลกและสิ่งก่อสร้าง",
    availableTags: ["Map"],
    productIds: [2, 7],
  },
  commands: {
    name: "คอมมานด์",
    description: "คำสั่งและระบบพื้นฐานทั่วไป",
    availableTags: ["CMD"],
    productIds: [8, 9, 10],
  },
  apps: {
    name: "แอพเสริม",
    description: "เครื่องมือช่วยเหลือนอกเกมสำหรับการจัดการและพัฒนา",
    availableTags: ["APP"],
    productIds: [11, 12, 13],
  },
  websites: {
    name: "เว็บไซต์",
    description: "ระบบเว็บไซต์ต่างๆตามความชอบ",
    availableTags: ["WEB"],
    productIds: [15, 16],
  },
}

// ฟังก์ชันช่วยเหลือ
export const getProductById = (id: number | string) => {
  return productsData[id as keyof typeof productsData]
}

export const getProductsByCategory = (categorySlug: string) => {
  const category = categoriesData[categorySlug as keyof typeof categoriesData]
  if (!category) return []

  return category.productIds.map((id) => ({
    id,
    ...productsData[id as keyof typeof productsData],
  }))
}

export const getFeaturedProducts = () => {
  // สินค้าแนะนำ (แอดออนที่มีจริง)
  return [1, 4, 5, 14].map((id) => ({
    id,
    ...productsData[id as keyof typeof productsData],
  }))
}

export const getAllProducts = () => {
  return Object.entries(productsData).map(([id, product]) => ({
    id: Number(id),
    ...product,
  }))
}

// สำหรับ favorites page
export const getProductsForFavorites = () => {
  const result: Record<string, any> = {}
  Object.entries(productsData).forEach(([id, product]) => {
    result[id] = {
      name: product.name,
      price: product.price,
      tags: product.tags,
      category: product.category,
      image: product.images[0], // ใช้รูปแรก
    }
  })
  return result
}
